#!/bin/bash
#MX-comfort-recolour
#Tool to edit colours in MX-comfort Fluxbox style
#V0.8.1 by Melber March 2022
#License: GPL-3.0+
#thanks to Fehlix, i_ri, Girafenaine, purplemoon and Jerry3904 @forum.mxlinux.org for help, tips and encouragement


#define some variables

TITLE="MX-comfort-recolour"
CLASS="mxcr"
ICONPATH="/usr/share/pixmaps/mxcr-icon.png"
#HELPPATH="/usr/share/pixmaps/mxcr-help.png"


#delete stylelist and tempclr after use
trap "rm -r "~/.fluxbox/scripts/tempdir" " EXIT


# Check if mxcr.txt exists in MX-comfort and MX-comfort-dark, create if false

if [ ! -f ~/.fluxbox/styles/MX-comfort/mxcr.txt ]; then

  printf "#0f56d9 #1d2324 #ffffff #ffffff #0f56d9 #CACDD0 #1d2324 #CACDD0 #c6c8c8 #1D2324 #EEEFF4 #ffffff #1D2324 #ffffff MX-comfort yes no" > ~/.fluxbox/styles/MX-comfort/mxcr.txt

fi


if [ ! -f ~/.fluxbox/styles/MX-comfort-dark/mxcr.txt ]; then

  printf "#0f56d9 #1d2324 #ffffff #ffffff #0f56d9 #CACDD0 #1d2324 #CACDD0 #c6c8c8 #1D2324 #1D2324 #ffffff #DEDFE3 #ffffff MX-comfort-dark yes no" > ~/.fluxbox/styles/MX-comfort-dark/mxcr.txt

fi


#create tempdir

if [ ! -d ~/.fluxbox/scripts/tempdir ]; then

  mkdir -p ~/.fluxbox/scripts/tempdir

fi


#read available styles

ls -d ~/.fluxbox/styles/*/mxcr.txt | cut -d '/' -f6- > ~/.fluxbox/scripts/tempdir/stylelist.txt
sed -i 's|/mxcr.txt||g' ~/.fluxbox/scripts/tempdir/stylelist.txt


#select starting style

BASESTYLE=$( yad --title="$TITLE" --class="$CLASS" --window-icon="$ICONPATH" --text="\n<b> Choose which style to use as a starting point</b>\n" --center --width=400 --height=300 --center --list --no-headers --separator=" " --column=Style < ~/.fluxbox/scripts/tempdir/stylelist.txt )

GETOUT=$(echo "$?")

if [ "$GETOUT" != 0 ]; then

  exit

fi


if [ -z "$BASESTYLE" ]; then

  yad --title="$TITLE" --class="$CLASS" --window-icon="$ICONPATH" --text="No starting style selected.\n\n<b>MX-comfort</b> will be used as the starting style." --button=OK --text-align=center --center --width=400 --height=200 --borders=20 \

  BASESTYLE=MX-comfort

fi


#read colours

cd ~/.fluxbox/styles/$BASESTYLE

read -r -a NEWCOLOURS < mxcr.txt

ACHL="${NEWCOLOURS[0]}"
ACTI="${NEWCOLOURS[1]}"
ACTXCOL="${NEWCOLOURS[2]}"
ACSY="${NEWCOLOURS[3]}"
ACGP="${NEWCOLOURS[4]}"
INHL="${NEWCOLOURS[5]}"
INTI="${NEWCOLOURS[6]}"
INTXCOL="${NEWCOLOURS[7]}"
INSY="${NEWCOLOURS[8]}"
INGP="${NEWCOLOURS[9]}"
MEBG="${NEWCOLOURS[10]}"
METXTI="${NEWCOLOURS[11]}"
METX="${NEWCOLOURS[12]}"
METXHL="${NEWCOLOURS[13]}"
NEWNAME="${NEWCOLOURS[14]}"
MAKECUR="${NEWCOLOURS[15]}"
MAKET2="${NEWCOLOURS[16]}"


# function to be called with yad button

color_picker() {
    local N=$1 C="$2"
    local YAD=(
            yad
            --title="mxcr-colour-selector"
            --class=color-select
            --window-icon=color-select
            --posx=200
            --posy=200
            --color
            --init-color="${C:=white}"
            )
    C=$("${YAD[@]}")
    (($?==0)) && echo "$N:$C"
}


# function to be called with help button

mxcrhelp() {
yad --title="MX-comfort-recolour help" --window-icon=/usr/share/pixmaps/mxcr-icon.png --borders=20 --center --width=700 --height=400 --image /usr/share/pixmaps/mxcr-help.png --size=fit --button="Return to Main Window":1 \

}

export -f color_picker mxcrhelp

#MAIN
#colour selection dialogue

MAIN=(yad --title="$TITLE" --class="$CLASS" --window-icon="$ICONPATH" --borders=20 --center --width=900 --height=400 --fixed --form --columns=7 --align=right --separator=" " --button="gtk-help":"bash -c mxcrhelp" --button="gtk-quit":1 --button="gtk-ok":0 \
--text="<b>\nEdit MX-comfort colours and create a new fluxbox style.\n\n</b>" \
--field="<b>Active Window</b>":LBL " " \
--field="Window Highlight":CLR "$ACHL" \
--field="Window Title":CLR "$ACTI" \
--field="Title Text":CLR "$ACTXCOL" \
--field="Window Symbol":CLR "$ACSY" \
--field="Window Grips":CLR "$ACGP" \
--field=" ":LBL " " \
--field=" ":LBL " " \
--field=" ":LBL " " \
--field=" ":LBL " " \
--field='!color-select':BTN '@bash -c "color_picker 2 %2;"'
--field='!color-select':BTN '@bash -c "color_picker 3 %3;"'
--field='!color-select':BTN '@bash -c "color_picker 4 %4;"'
--field='!color-select':BTN '@bash -c "color_picker 5 %5;"'
--field='!color-select':BTN '@bash -c "color_picker 6 %6;"'
--field=" ":LBL " " \
--field=" ":LBL " " \
--field=" ":LBL " " \
--field="<b>Inctive Window</b>":LBL " " \
--field="Window Highlight":CLR "$INHL" \
--field="Window Title":CLR "$INTI" \
--field="Title Text":CLR "$INTXCOL" \
--field="Window Symbol":CLR "$INSY" \
--field="Window Grips":CLR "$INGP" \
--field=" ":LBL " " \
--field=" ":LBL " " \
--field=" ":LBL " " \
--field=" ":LBL " " \
--field='!color-select':BTN '@bash -c "color_picker 20 %20;"'
--field='!color-select':BTN '@bash -c "color_picker 21 %21;"'
--field='!color-select':BTN '@bash -c "color_picker 22 %22;"'
--field='!color-select':BTN '@bash -c "color_picker 23 %23;"'
--field='!color-select':BTN '@bash -c "color_picker 24 %24;"'
--field=" ":LBL " " \
--field=" ":LBL " " \
--field=" ":LBL " " \
--field="<b>Fluxbox Menu</b>":LBL " " \
--field="Menu Background":CLR "$MEBG" \
--field="Menu Title Text":CLR "$METXTI" \
--field="Menu Text":CLR "$METX" \
--field="Menu HL Text":CLR "$METXHL" \
--field=" ":LBL " " \
--field=" ":LBL " " \
--field=" ":LBL " " \
--field=" ":LBL " " \
--field=" ":LBL " " \
--field='!color-select':BTN '@bash -c "color_picker 38 %38;"'
--field='!color-select':BTN '@bash -c "color_picker 39 %39;"'
--field='!color-select':BTN '@bash -c "color_picker 40 %40;"'
--field='!color-select':BTN '@bash -c "color_picker 41 %41;"'
--field=" ":LBL " " \
--field=" ":LBL " " \
--field=" ":LBL " " \
--field=" ":LBL " " \
--field="<b>  Name for new style        </b>":LBL " " \
--field=" " ""$NEWNAME"" \
--field="<b>  Make new style current?</b>":LBL " " \
--field=" ":CB "yes!no" \
--field="<b>  Create matching panel?</b>":LBL " " \
--field=" ":CB "no!yes" \
)

COLOURS=$("${MAIN[@]}")
    (($?==0)) && echo "$COLOURS" > ~/.fluxbox/scripts/tempdir/tempmain.txt

GETOUT=$(echo "$?")

if [ "$GETOUT" = 1 ]; then

  exit

elif [ "$GETOUT" = 0 ]; then

  cd ~/.fluxbox/scripts/tempdir

  read -r -a NEWCOLOURS < tempmain.txt

  ACHL="${NEWCOLOURS[0]}"
  ACTI="${NEWCOLOURS[1]}"
  ACTXCOL="${NEWCOLOURS[2]}"
  ACSY="${NEWCOLOURS[3]}"
  ACGP="${NEWCOLOURS[4]}"
  INHL="${NEWCOLOURS[5]}"
  INTI="${NEWCOLOURS[6]}"
  INTXCOL="${NEWCOLOURS[7]}"
  INSY="${NEWCOLOURS[8]}"
  INGP="${NEWCOLOURS[9]}"
  MEBG="${NEWCOLOURS[10]}"
  METXTI="${NEWCOLOURS[11]}"
  METX="${NEWCOLOURS[12]}"
  METXHL="${NEWCOLOURS[13]}"
  NEWNAME="${NEWCOLOURS[14]}"
  MAKECUR="${NEWCOLOURS[15]}"
  MAKET2="${NEWCOLOURS[16]}"

fi


#check style names yes no

if [ "$NEWNAME" = 'yes' -o "$NEWNAME" = 'no' ]; then

  MAKET2="$MAKECUR"
  MAKECUR="$NEWNAME"  

  NEWNAME=$(yad --title="$TITLE" --class="$CLASS" --window-icon="$ICONPATH" --width=400 --height=200 --fixed --text="No Style name !" --form --center --borders=20 --separator="" \
  --field="<b>Name for new style</b>":LBL " " \
  --field=" " "New style name" )
    
    GETOUT=$(echo "$?")

    if [ "$GETOUT" != 0 ]; then

    exit

    fi

fi


#check new style name is not empty and forbid MX-comfort overwrite

while [ -z "$NEWNAME" -o "$NEWNAME" = 'MX-comfort' -o "$NEWNAME" = 'MX-comfort-dark' ]; do

  NEWNAME=$(yad --title="$TITLE" --class="$CLASS" --window-icon="$ICONPATH" --width=400 --height=200 --fixed --text="Style name "$NEWNAME" is protected. Choose another name." --form --center --borders=20 --separator="" \
  --field="<b>Name for new style</b>":LBL " " \
  --field=" " "$NEWNAME-new" )

    GETOUT=$(echo "$?")

    if [ "$GETOUT" != 0 ]; then

    exit

    fi

done


#check if new style name exists, if yes ask if overwrite or different style name

while [ -d ~/.fluxbox/styles/$NEWNAME ]; do

  yad --title="$TITLE" --class="$CLASS" --window-icon="$ICONPATH" --width=400 --fixed --text="A Style with this name already exists. \n\nDo you want to overwrite <b>"$NEWNAME"</b>\nor save as a different style name\n" --button="Overwrite $NEWNAME":2 --button="Save as different style name":3 --text-align=center --center --borders=20\

    case $? in

    2) rm -r ~/.fluxbox/styles/$NEWNAME   ;;

    3) NEWNAME=$(yad --title="$TITLE" --class="$CLASS" --window-icon="$ICONPATH" --width=400 --height=200 --fixed --form --center --borders=20 --separator="" \
    --field="<b>Name for new style</b>":LBL " " \
    --field=" " "$NEWNAME-new" )    ;;

    252) exit 0    ;;

  esac
  
done


#rewrite tint2 warning

if [ "$MAKET2" = yes ]; then

  yad --title="$TITLE" --class="$CLASS" --window-icon="$ICONPATH" --width=400 --fixed --text="<b>Attention!</b> \n\nYou selected to create a matching Tint2 panel.\nThe tool assumes you are using the default MX-comfort Tint2 panel.\n\nIf you have edited this panel or selected a different panel,\ncreating a matching panel may have unexpected results.\n\nPlease confirm if you want to create a matching tint2 panel?\n" --button="Create matching tint2 Panel":2 --button="Do not create matching tint2 panel":3 --text-align=center --center --borders=20\

    case $? in

    2) MAKET2="yes"   ;;

    3) MAKET2="no"    ;;

    252) exit 0    ;;

  esac
  
fi


#Copy MX-comfort to new style name

echo "$BASESTYLE"

if [[ $BASESTYLE = MX-comfort-plus* ]]; then

  cp -r ~/.fluxbox/styles/MX-comfort-plus ~/.fluxbox/styles/$NEWNAME
  
else

  cp -r ~/.fluxbox/styles/MX-comfort ~/.fluxbox/styles/$NEWNAME

fi


#move to new style directory and amend name and grips in theme config file

cd ~/.fluxbox/styles/$NEWNAME

echo ""$ACHL" "$ACTI" "$ACTXCOL" "$ACSY" "$ACGP" "$INHL" "$INTI" "$INTXCOL" "$INSY" "$INGP" "$MEBG" "$METXTI" "$METX" "$METXHL" "$NEWNAME" "$MAKECUR" "$MAKET2"" > ~/.fluxbox/styles/$NEWNAME/mxcr.txt

sed -i "s/MX-comfort/$NEWNAME/g" theme.cfg
sed -i "s/menu.frame.color:                    #EEEFF4/menu.frame.color:                    $MEBG/g" theme.cfg
sed -i "s/menu.title.color:                    #1D2324/menu.title.color:                    $ACTI/g" theme.cfg
sed -i "s/menu.hilite.color:                   #0f56d9/menu.hilite.color:                   $ACHL/g" theme.cfg
sed -i "s/menu.frame.textColor:                #1D2324/menu.frame.textColor:                   $METX/g" theme.cfg
sed -i "s/menu.title.textColor:                #ffffff/menu.title.textColor:                   $METXTI/g" theme.cfg
sed -i "s/menu.hilite.textColor:               #ffffff/menu.hilite.textColor:                   $METXHL/g" theme.cfg
sed -i "s/window.label.focus.textColor:        #ffffff/window.label.focus.textColor:                   $ACTXCOL/g" theme.cfg
sed -i "s/window.label.unfocus.textColor:      #CACDD0/window.label.unfocus.textColor:                   $INTXCOL/g" theme.cfg
sed -i "s/window.grip.focus.color:             #0f56d9/window.grip.focus.color:             $ACGP/g" theme.cfg
sed -i "s/window.grip.unfocus.color:           #1D2324/window.grip.unfocus.color:           $INGP/g" theme.cfg
sed -i "s/window.handle.focus.color:           #1D2324/window.handle.focus.color:           $ACTI/g" theme.cfg
sed -i "s/window.handle.unfocus.color:         #1D2324/window.handle.unfocus.color:         $INTI/g" theme.cfg


#move to pixmap directory and amend colours

cd ~/.fluxbox/styles/$NEWNAME/pixmaps

sed -i "s/#0f56d9/$ACHL/g" *
sed -i "s/#1d2324/$ACTI/g" *
sed -i "s/#ffffff/$ACSY/g" *
sed -i "s/#CACDD0/$INHL/g" *-inactive.xpm
sed -i "s/#1D2324/$INTI/g" *-inactive.xpm
sed -i "s/#c6c8c8/$INSY/g" *-inactive.xpm


#copy and amend tint2 panel

if [ "$MAKET2" = yes ]; then

cd ~/.config/tint2
cp -r ~/.config/tint2/tint2rc ~/.config/tint2/$NEWNAME-tint2rc
sed -i "s/#0f56d9/$ACHL/g" $NEWNAME-tint2rc
rm tint2-sessionfile
echo '$HOME'"/.config/tint2/$NEWNAME-tint2rc" >> tint2-sessionfile
killall tint2
tint2 -c ~/.config/tint2/$NEWNAME-tint2rc >/dev/null 2>&1 & disown

fi


#set new style as current

if [ "$MAKECUR" = yes ]; then

  sed -i -r "/^(session.styleFile:).*/s::\1    ~/.fluxbox/styles/$NEWNAME:"  ~/.fluxbox/init

  fluxbox-remote restart

  yad --title="$TITLE" --class="$CLASS" --window-icon="$ICONPATH" --width=400 --height=200 --fixed --center --borders=20 --text="All done!\n<b>"$NEWNAME"</b> has been set as the current style." --text-align=center --button="OK" \

fi


if [ "$MAKECUR" = no ]; then

  yad --title="$TITLE" --class="$CLASS" --window-icon="$ICONPATH" --width=400 --height=250 --fixed --center --borders=20 --text="All done!\n<b>"$NEWNAME"</b> style has been created.\n\nYou can change styles with \n<b>Fluxbox menu  >  Appearance  >  Style</b> \n\nand refresh with \n<b>Fluxbox menu  >  Leave  >  Refresh</b> " --text-align=center --button="OK" \

fi

exit
