#!/bin/bash
#mxlook is an app to save and restore the look of MX-Linux Fluxbox
#V0.01 by Melber April 2022

#License: GPL-3.0+
#mxcr-icon based on yad icon from papirus icon set

#paths
#theme and icons ~/.config/gtk-3.0/settings.ini


#define some variables

TITLE="MX-look"
CLASS="mxlook"
MXLKPATH="$HOME/.config/mxlook"
ICONPATH="/usr/share/pixmaps/mxcr-icon.png"
#HELPPATH="/usr/share/pixmaps/mxrr-help.png"


#delete stylelist and tempclr after use
#trap "rm -r "$MXLKPATH/tempdir" " EXIT

#
if [ ! -d $MXLKPATH ]; then

mkdir $MXLKPATH

fi

#create tempdir

if [ ! -d $MXLKPATH/tempdir ]; then

  mkdir -p $MXLKPATH/tempdir

fi

#make Default look file

if [ ! -f $MXLKPATH/default.look ]; then

echo ""$LKTHEME" "$LKICON" "$LKFLUXSTYLE" "$LKTINT" "$LKROFI" "$LKBACK"" > $MXLKPATH/default.look

fi


#################################
# function save look

save_look() {
#define some variables

TITLE="MX-look"
CLASS="mxlook"
MXLKPATH="$HOME/.config/mxlook"
ICONPATH="/usr/share/pixmaps/mxcr-icon.png"

#read current look components

#theme and icons
	#$HOME/.config/gtk-3.0/settings.ini

	#gtk-theme-name=*
	#gtk-icon-theme-name=*
	
LKTHEME="$(grep "gtk-theme-name" $HOME/.config/gtk-3.0/settings.ini)"
#LKTH="$(echo "$LKTHEME" | (IFS="=" read -r var1 var2; echo -e "$var2"))"


LKICON="$(grep "gtk-icon-theme-name" $HOME/.config/gtk-3.0/settings.ini)"
#LKIC="$(echo "$LKICON" | (IFS="=" read -r var1 var2; echo -e "$var2"))"

#fluxbox style


LKFLUXSTYLE="$(grep "styles" $HOME/.fluxbox/init)"
#LKFS="$(echo "$LKFLUXSTYLE" | (IFS="/" read -r var1 var2 var3 var4 var5 var6; echo -e "$var6"))"

#tint2


LKTINT="$(grep "tint2" $HOME/.config/tint2/tint2-sessionfile)"
#LKTI="$(echo "$LKTINT" | (IFS="/" read -r var1 var2 var3 var4 var5; echo -e "$var4"))"
#LKTI=basename "$LKTINT"


#rofi


LKROFI="$(grep "themes" $HOME/.config/rofi/config.rasi)"
#LKRO="$(echo "$LKROFI" | (IFS="/" read -r var1 var2 var3 var4 var5 var6 var7; echo -e "$var7"))"
#LKRO=basename "$LKROFI"


#background

LKBACK="$(grep "file=" $HOME/.config/nitrogen/bg-saved.cfg)"
#LKBG=basename "$LKBACK"


#make temp file
echo ""$LKTHEME" "$LKICON" "$LKFLUXSTYLE" "$LKTINT" "$LKROFI" "$LKBACK"" > $MXLKPATH/tempdir/looktmp.txt

#amend temp
cd $MXLKPATH/tempdir

sed -i "s/gtk-theme-name\=/ /g" looktmp.txt
sed -i "s/gtk-icon-theme-name\=/ /g" looktmp.txt
sed -i "s/session\.styleFile\:/ /g" looktmp.txt
sed -i "s/\@import/ /g" looktmp.txt
sed -i "s/file\=/ /g" looktmp.txt
#sed -i "s/\.tint2rc/ /g" looktmp.txt
#sed -i "s/\.rasi\"/ /g" looktmp.txt
sed -i "s/\"/ /g" looktmp.txt
#sed -i "s/\.jpg/ /g" looktmp.txt


#read temp

read -r -a YADFILL < looktmp.txt

LKTH="${YADFILL[0]}"
LKIC="${YADFILL[1]}"
LKFS="${YADFILL[2]}"
LKTI="${YADFILL[3]}"
LKRO="${YADFILL[4]}"
LKBG="${YADFILL[5]}"


#MAIN
#color selection dialogue

MAIN=(yad --title="$TITLE" --class="$CLASS" --window-icon="$ICONPATH" --borders=20 --center --width=600 --height=400 --fixed --form --columns=1 --align=left --separator="_" --button="gtk-quit":1 --button="Save Look":0 \
--text="
<b>Current Settings.\n</b>
GTK Theme:		<b>"$LKTH"</b>\n
Gtk Icons:		<b>"$LKIC"</b>\n
Fluxbox Style:	<b>"$LKFS"</b>\n
Tint2:			<b>"$LKTI"</b>\n
Rofi:			<b>"$LKRO"</b>\n
Wallpaper:		<b>"$LKBG"</b>\n"
--field="Save Look as" "New-Look-Name"\
)
NEWNAME=$("${MAIN[@]}")
GETOUT=$(echo "$?")

if [ "$GETOUT" != 0 ]; then

  exit

elif [ "$GETOUT" = 0 ]; then

    echo ""$LKTHEME","$LKICON","$LKFLUXSTYLE","$LKTINT","$LKROFI","$LKBACK"" > $MXLKPATH/"$NEWNAME".look

  yad --title="$TITLE" --class="$CLASS" --window-icon="$ICONPATH" --width=400 --height=250 --fixed --center --borders=20 --text="All done!\n\nLook has been saved as <b>$NEWNAME</b>" --text-align=center --button="OK" \

fi

exit
}

###################
#function restore look

restore_look() {
#define some variables

TITLE="MX-look"
CLASS="mxlook"
MXLKPATH="$HOME/.config/mxlook"
ICONPATH="/usr/share/pixmaps/mxcr-icon.png"


#read saved looks
cd $MXLKPATH
ls -f *_.look > $MXLKPATH/tempdir/looklist.txt
#sed -i 's|_.look||g' $MXLKPATH/tempdir/looklist.txt


#select look to restore

LOOKRESTORE=$( yad --title="$TITLE" --class="$CLASS" --window-icon="$ICONPATH" --text="\n<b> Choose which look to restore</b>\n" --center --width=400 --height=300 --center --list --no-headers --column=Style --separator="" < $MXLKPATH/tempdir/looklist.txt )

GETOUT=$(echo "$?")

if [ "$GETOUT" != 0 ]; then

  exit

fi

#read Settings
#LOOKRESTORE=$LOOKRESTORE_.look
cd $MXLKPATH

read -r -a LKRE < $LOOKRESTORE
IFS=","

LKTHEME="${LKRE[0]}"
LKICON="${LKRE[1]}"
LKFLUXSTYLE="${LKRE[2]}"
LKTINT="${LKRE[3]}"
LKROFI="${LKRE[4]}"
LKBACK="${LKRE[5]}"

echo ""$LKTHEME" "$LKICON" "$LKFLUXSTYLE" "$LKTINT" "$LKROFI" "$LKBACK""

exit

#Edit Config files

#gtk
#cd ~/.config/gtk-3.0
#sed -i "s/gtk-theme-name\=*/"$LKTHEME"/g" settings.ini
#sed -i "s/gtk-icon-theme-name\=*/"$LKICON"/g" settings.ini
sed -e "s/^gtk-theme-name=.*/gtk-theme-name="$LKTHEME"/" -i ~/.config/gtk-3.0/settings.ini

#fluxbox
#cd ~/.config/fluxbox
#  sed -i "s/session.styleFile:*/"$LKFLUXSTYLE"/g"  ~/.fluxbox/init
sed -i -r "/^(session.styleFile:).*/s::\1    ~/.fluxbox/styles/$LKFLUXSTYLE:"  ~/.fluxbox/init

#tint
#cd ~/.config/tint2
#rm tint2-sessionfile
#echo "$LKTINT" >> tint2-sessionfile

#rofi
#cd $HOME/.config/rofi/
#sed -i "s/\@import*/"$LKROFI"/g" config.rasi

#background
#cd $HOME/.config/nitrogen
#sed -i "s/file\=*/$LKBACK/g" bg-saved.cfg

#restart


#gtk bash
function reload_gtk_theme() {
  theme=$(gsettings get org.gnome.desktop.interface gtk-theme)
  gsettings set org.gnome.desktop.interface gtk-theme ''
  sleep 1
  gsettings set org.gnome.desktop.interface gtk-theme $theme
}

reload_gtk_theme


#fluxbox-remote restart

#killall tint2

nitrogen --restore
#nitrogen --set-zoom-fill "$LKBACK"


}

export -f save_look restore_look

yad --title="$TITLE" --class="$CLASS" --window-icon="$ICONPATH" --width=400 --height=200 --fixed --center --borders=20 \
--text="<b>You can save the current look or restore a saved look</b>\n\nA look is comprised of the following elements\n- Gtk-Theme\n- Gtk-Icon\n- Fluxbox Style\n- Tint2 Panel\n- Rofi Theme\n- Wallpaper\n\n" --text-align=center --button="gtk-close" --button="Restore Look":"bash -c restore_look" --button="Save Current Look":"bash -c save_look" \

